import { jsPDF } from "jspdf";
import "jspdf-autotable";

export const generatePDFReport = (transactions, stats = {}) => {
  const doc = new jsPDF();
  
  // Header section
  doc.setFont("Helvetica", "bold");
  doc.setFontSize(22);
  doc.setTextColor(15, 23, 42); // slate-900
  doc.text("SentinelStream", 14, 20);
  
  doc.setFontSize(10);
  doc.setFont("Helvetica", "normal");
  doc.setTextColor(100, 116, 139); // slate-500
  doc.text("FRAUD INTELLIGENCE & TRANSACTION REPORT", 14, 25);
  
  doc.setDrawColor(226, 232, 240); // slate-200
  doc.line(14, 28, 196, 28);
  
  // Date and Metadata
  const now = new Date();
  const dateStr = now.toLocaleString();
  doc.setFontSize(9);
  doc.setTextColor(71, 85, 105); // slate-600
  doc.text(`Report Generated: ${dateStr}`, 14, 35);
  doc.text("Generated By: SentinelStream Admin Console", 14, 40);
  
  // Summary Cards Box
  doc.setDrawColor(226, 232, 240);
  doc.setFillColor(248, 250, 252); // slate-50
  doc.rect(14, 46, 182, 24, "F");
  
  doc.setFont("Helvetica", "bold");
  doc.setFontSize(9);
  doc.setTextColor(15, 23, 42);
  doc.text("Total Processed", 20, 52);
  doc.text("Fraud Rate", 70, 52);
  doc.text("Safe Volume", 120, 52);
  doc.text("Fraud Cases", 160, 52);
  
  doc.setFont("Helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(37, 99, 235); // blue-600
  doc.text(`INR ${stats.total_amount_processed || 0}`, 20, 60);
  doc.setTextColor(239, 68, 68); // red-500
  doc.text(stats.fraud_rate || "0%", 70, 60);
  doc.setTextColor(34, 197, 94); // green-500
  doc.text(String(stats.safe_transactions || 0), 120, 60);
  doc.setTextColor(239, 68, 68);
  doc.text(String(stats.fraud_transactions || 0), 160, 60);
  
  // Table Section Header
  doc.setFont("Helvetica", "bold");
  doc.setFontSize(12);
  doc.setTextColor(15, 23, 42);
  doc.text("Transaction Register Summary", 14, 82);
  
  // Setup Table Columns & Rows
  const tableColumn = ["ID", "User ID", "Amount", "Location", "Status", "Timestamp"];
  const tableRows = [];
  
  transactions.forEach((tx) => {
    const txData = [
      tx.id,
      tx.user_id,
      `INR ${tx.amount}`,
      tx.location,
      tx.status,
      tx.timestamp || tx.date || "-"
    ];
    tableRows.push(txData);
  });
  
  doc.autoTable({
    head: [tableColumn],
    body: tableRows,
    startY: 86,
    theme: "striped",
    headStyles: { fillColor: [15, 23, 42], fontSize: 9, fontStyle: "bold" },
    bodyStyles: { fontSize: 9 },
    columnStyles: {
      0: { cellWidth: 15 },
      1: { cellWidth: 20 },
      2: { cellWidth: 35 },
      3: { cellWidth: 40 },
      4: { cellWidth: 30 },
      5: { cellWidth: 42 }
    },
    didDrawCell: (data) => {
      if (data.column.index === 4 && data.cell.section === "body") {
        const status = data.cell.raw;
        if (status === "SAFE") {
          doc.setTextColor(34, 197, 94); // green-500
        } else if (status === "FRAUD") {
          doc.setTextColor(239, 68, 68); // red-500
        } else if (status === "HIGH_RISK") {
          doc.setTextColor(245, 158, 11); // yellow-500
        }
      }
    }
  });
  
  // Save PDF
  doc.save(`sentinelstream-report-${now.toISOString().split("T")[0]}.pdf`);
};
